package constant

var (
	EVENT_SEVERITY_INFO     string = "INFO"
	EVENT_SEVERITY_ERROR    string = "ERROR"
	EVENT_SEVERITY_ALERT    string = "ALERT"
	EVENT_SEVERITY_CRITICAL string = "CRITICAL"
	EVENT_SEVERITY_WARNING  string = "WARNING"
	EVENT_SEVERITY_FATAL    string = "FATAL"

	EVENT_SENSETIVITY_LEVEL_LOW    string = "LOW"
	EVENT_SENSETIVITY_LEVEL_HIGH   string = "HIGH"
	EVENT_SENSETIVITY_LEVEL_MEDIUM string = "MEDIUM"

	EVENT_INTEGRITY_STATUS_VALID   string = "VALID"
	EVENT_INTEGRITY_STATUS_INVALID string = "INVALID"
)

const (
	HANDER_UPLOAD string = "Handler:Upload"
	SERVICE_UPLOAD string = "Service:Upload"
)
